#!/usr/bin/env node

//
// This code generated by OpenAI and Claude with the instruction and guidance of ejb (Richard Edwards)
// It should be uses as proof of concept and may require additional hardening/validation/testing for large scale production use
//

import { spawn } from "node:child_process";
import { promises as fs } from "node:fs";
import path from "node:path";
import process from "node:process";
import crypto from "node:crypto";

import { Server } from "/app/node_modules/@modelcontextprotocol/sdk/dist/esm/server/index.js";
import { StdioServerTransport } from "/app/node_modules/@modelcontextprotocol/sdk/dist/esm/server/stdio.js";
import {
  CallToolRequestSchema,
  ListToolsRequestSchema
} from "/app/node_modules/@modelcontextprotocol/sdk/dist/esm/types.js";

const REPOS_BASE_DIR = process.env.REPOS_BASE_DIR || "/repos";
const HOST_REPOS_BASE_DIR = process.env.HOST_REPOS_BASE_DIR || "/opt/redback/repos";
const JOBS_BASE_DIR = process.env.JOBS_BASE_DIR || path.join(REPOS_BASE_DIR, "logs", "security-jobs");
const SEMGREP_IMAGE = process.env.SEMGREP_IMAGE || "semgrep/semgrep:1.159.0";
const SEMGREP_JOBS = String(process.env.SEMGREP_JOBS || "2");
const SEMGREP_PER_FILE_TIMEOUT = String(process.env.SEMGREP_PER_FILE_TIMEOUT || "2");
const SEMGREP_TIMEOUT_THRESHOLD = String(process.env.SEMGREP_TIMEOUT_THRESHOLD || "1");
const SEMGREP_MAX_TARGET_BYTES = String(process.env.SEMGREP_MAX_TARGET_BYTES || "500000");
const JOB_RETENTION_LIMIT = Number(process.env.JOB_RETENTION_LIMIT || "100");

function normalizeRepoInput(repo) {
  if (!repo || typeof repo !== "string") {
    throw new Error("Missing required field: repo");
  }

  let value = repo.trim();

  if (value === "/repos") {
    throw new Error("repo must identify a repository, not /repos itself");
  }

  if (value.startsWith("/repos/")) {
    value = value.slice("/repos/".length);
  }

  value = value.replace(/^\/+/, "").replace(/\/+$/, "");

  if (!value) {
    throw new Error("repo must not be empty");
  }

  if (value.includes("\\") || value.includes("..") || value.includes("/")) {
    throw new Error(
      "repo must be a repository directory name under /repos, for example 'redback-smartbike-iot'"
    );
  }

  return value;
}

function normalizeScope(scope) {
  if (scope === undefined || scope === null || scope === "") {
    return ".";
  }
  if (typeof scope !== "string") {
    throw new Error("scope must be a string");
  }
  return scope.trim() || ".";
}

function profileToConfigs(profile) {
  const p = String(profile || "security").toLowerCase();

  if (p === "security") return ["--config=p/security-audit"];
  if (p === "secrets") return ["--config=p/secrets"];
  if (p === "full") {
    return [
      "--config=p/security-audit",
      "--config=p/secrets",
      "--config=p/owasp-top-ten"
    ];
  }

  throw new Error("Unsupported profile. Use one of: security, secrets, full");
}

function safeResolve(repo, scope = ".") {
  const safeRepo = normalizeRepoInput(repo);
  const safeScope = normalizeScope(scope);

  const repoPath = path.resolve(REPOS_BASE_DIR, safeRepo);
  const targetPath = path.resolve(repoPath, safeScope);

  if (!targetPath.startsWith(repoPath)) {
    throw new Error("Scope escapes repository root");
  }

  const relativeTarget = path.relative(repoPath, targetPath);
  const containerTargetPath =
    relativeTarget && relativeTarget !== "."
      ? path.posix.join("/repos", safeRepo, relativeTarget.split(path.sep).join("/"))
      : path.posix.join("/repos", safeRepo);

  return {
    safeRepo,
    safeScope,
    repoPath,
    targetPath,
    containerTargetPath
  };
}

async function pathExists(p) {
  try {
    await fs.access(p);
    return true;
  } catch {
    return false;
  }
}

async function ensureDir(p) {
  await fs.mkdir(p, { recursive: true });
}

async function readJson(filePath, fallback = null) {
  try {
    const text = await fs.readFile(filePath, "utf8");
    return JSON.parse(text);
  } catch {
    return fallback;
  }
}

async function writeJson(filePath, data) {
  await fs.writeFile(filePath, JSON.stringify(data, null, 2) + "\n", "utf8");
}

function summarizeFindings(findings) {
  const summary = {
    findings_total: findings.length,
    critical: 0,
    high: 0,
    medium: 0,
    low: 0,
    info: 0,
    unknown: 0
  };

  for (const finding of findings) {
    const severity = String(finding.severity || "").toUpperCase();
    if (severity === "CRITICAL") summary.critical += 1;
    else if (severity === "HIGH" || severity === "ERROR") summary.high += 1;
    else if (severity === "MEDIUM" || severity === "WARNING") summary.medium += 1;
    else if (severity === "LOW") summary.low += 1;
    else if (severity === "INFO" || severity === "NOTICE") summary.info += 1;
    else summary.unknown += 1;
  }

  return summary;
}

function makeJobId(repo) {
  const ts = new Date().toISOString().replace(/[:.]/g, "-");
  const rand = crypto.randomBytes(4).toString("hex");
  return `scan-${ts}-${repo}-${rand}`;
}

function getJobPaths(jobId) {
  const dir = path.join(JOBS_BASE_DIR, jobId);
  return {
    dir,
    meta: path.join(dir, "job.json"),
    stdout: path.join(dir, "stdout.json"),
    stderr: path.join(dir, "stderr.log")
  };
}

async function listRepos() {
  const entries = await fs.readdir(REPOS_BASE_DIR, { withFileTypes: true });
  const repos = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    if (entry.name.startsWith(".")) continue;
    if (entry.name === "logs") continue;

    repos.push({
      repo: entry.name,
      path: path.join(REPOS_BASE_DIR, entry.name)
    });
  }

  repos.sort((a, b) => a.repo.localeCompare(b.repo));

  return {
    success: true,
    repos_base_dir: REPOS_BASE_DIR,
    repos
  };
}

async function cleanupOldJobs() {
  await ensureDir(JOBS_BASE_DIR);
  const entries = await fs.readdir(JOBS_BASE_DIR, { withFileTypes: true });
  const dirs = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const full = path.join(JOBS_BASE_DIR, entry.name);
    const stat = await fs.stat(full);
    dirs.push({ name: entry.name, full, mtimeMs: stat.mtimeMs });
  }

  dirs.sort((a, b) => b.mtimeMs - a.mtimeMs);

  for (const old of dirs.slice(JOB_RETENTION_LIMIT)) {
    await fs.rm(old.full, { recursive: true, force: true });
  }
}

async function startScanJob({ repo, scope = ".", profile = "security" }) {
  const {
    safeRepo,
    safeScope,
    repoPath,
    targetPath,
    containerTargetPath
  } = safeResolve(repo, scope);

  if (!(await pathExists(repoPath))) {
    throw new Error(
      `Repository not found in container view: ${repoPath}. Call repo_list to see available repositories.`
    );
  }

  if (!(await pathExists(targetPath))) {
    throw new Error(`Target path does not exist in container view: ${targetPath}`);
  }

  await ensureDir(JOBS_BASE_DIR);
  await cleanupOldJobs();

  const jobId = makeJobId(safeRepo);
  const paths = getJobPaths(jobId);
  await ensureDir(paths.dir);

  const configs = profileToConfigs(profile);

  const initialMeta = {
    success: true,
    job_id: jobId,
    status: "queued",
    repo: safeRepo,
    scope: safeScope,
    profile,
    created_at: new Date().toISOString(),
    started_at: null,
    finished_at: null,
    repo_path: repoPath,
    target_path: targetPath,
    container_target_path: containerTargetPath,
    jobs_base_dir: JOBS_BASE_DIR,
    host_repos_base_dir: HOST_REPOS_BASE_DIR,
    image: SEMGREP_IMAGE,
    pid: null,
    exit_code: null,
    summary: null,
    error: null
  };

  await writeJson(paths.meta, initialMeta);
  await fs.writeFile(paths.stderr, "", "utf8");

  const dockerArgs = [
    "run",
    "--rm",
    "-v",
    `${HOST_REPOS_BASE_DIR}:/repos:ro`,
    "-w",
    "/repos",
    "-e",
    "SEMGREP_ENABLE_VERSION_CHECK=0",
    "-e",
    "SEMGREP_SEND_METRICS=off",
    "-e",
    `HTTP_PROXY=${process.env.HTTP_PROXY || ""}`,
    "-e",
    `HTTPS_PROXY=${process.env.HTTPS_PROXY || ""}`,
    "-e",
    `NO_PROXY=${process.env.NO_PROXY || ""}`,
    SEMGREP_IMAGE,
    "semgrep",
    "scan",
    "--json",
    "--disable-version-check",
    "--metrics=off",
    "--optimizations=all",
    "--jobs",
    SEMGREP_JOBS,
    "--timeout",
    SEMGREP_PER_FILE_TIMEOUT,
    "--timeout-threshold",
    SEMGREP_TIMEOUT_THRESHOLD,
    "--max-target-bytes",
    SEMGREP_MAX_TARGET_BYTES,
    "--exclude=node_modules",
    "--exclude=.git",
    "--exclude=dist",
    "--exclude=build",
    "--exclude=.venv",
    "--exclude=vendor",
    "--exclude=coverage",
    "--exclude=.next",
    "--exclude=.cache",
    "--exclude=target",
    ...configs,
    containerTargetPath
  ];

  const child = spawn("docker", dockerArgs, {
    detached: true,
    stdio: ["ignore", "pipe", "pipe"],
    env: { ...process.env }
  });

  const stdoutChunks = [];
  const stderrChunks = [];

  child.stdout.on("data", (chunk) => {
    stdoutChunks.push(chunk);
  });

  child.stderr.on("data", (chunk) => {
    stderrChunks.push(chunk);
  });

  const runningMeta = {
    ...initialMeta,
    status: "running",
    started_at: new Date().toISOString(),
    pid: child.pid
  };

  await writeJson(paths.meta, runningMeta);

  child.on("close", async (code) => {
    const stdout = Buffer.concat(stdoutChunks).toString("utf8");
    const stderr = Buffer.concat(stderrChunks).toString("utf8");

    await fs.writeFile(paths.stderr, stderr, "utf8");

    let finalMeta = await readJson(paths.meta, runningMeta);
    finalMeta.exit_code = code;
    finalMeta.finished_at = new Date().toISOString();

    if (![0, 1].includes(code)) {
      finalMeta.status = "failed";
      finalMeta.error = `Semgrep failed with exit code ${code}`;
      await writeJson(paths.meta, finalMeta);
      return;
    }

    try {
      const parsed = stdout.trim() ? JSON.parse(stdout) : {};
      await writeJson(paths.stdout, parsed);

      const findings = (parsed.results || []).map((item) => ({
        rule_id: item.check_id || null,
        severity: item.extra?.severity || null,
        message: item.extra?.message || null,
        path: item.path || null,
        start_line: item.start?.line || null,
        end_line: item.end?.line || null
      }));

      finalMeta.status = "completed";
      finalMeta.summary = {
        ...summarizeFindings(findings),
        errors_total: (parsed.errors || []).length
      };
      finalMeta.error = null;
      await writeJson(paths.meta, finalMeta);
    } catch (err) {
      finalMeta.status = "failed";
      finalMeta.error = `Failed to parse Semgrep JSON output: ${err.message}`;
      await writeJson(paths.meta, finalMeta);
    }
  });

  child.unref();

  return {
    success: true,
    job_id: jobId,
    status: "queued",
    repo: safeRepo,
    scope: safeScope,
    profile,
    created_at: initialMeta.created_at
  };
}

async function getJobStatus({ job_id }) {
  if (!job_id || typeof job_id !== "string") {
    throw new Error("Missing required field: job_id");
  }

  const paths = getJobPaths(job_id);
  const meta = await readJson(paths.meta);

  if (!meta) {
    throw new Error(`Job not found: ${job_id}`);
  }

  return {
    success: true,
    job_id,
    status: meta.status,
    created_at: meta.created_at,
    started_at: meta.started_at,
    finished_at: meta.finished_at,
    repo: meta.repo,
    scope: meta.scope,
    profile: meta.profile,
    summary: meta.summary,
    error: meta.error,
    exit_code: meta.exit_code,
    pid: meta.pid
  };
}

async function getJobResult({ job_id }) {
  if (!job_id || typeof job_id !== "string") {
    throw new Error("Missing required field: job_id");
  }

  const paths = getJobPaths(job_id);
  const meta = await readJson(paths.meta);

  if (!meta) {
    throw new Error(`Job not found: ${job_id}`);
  }

  if (meta.status !== "completed") {
    return {
      success: false,
      job_id,
      status: meta.status,
      error: meta.error || "Job is not completed yet"
    };
  }

  const parsed = await readJson(paths.stdout, {});
  const findings = (parsed.results || []).map((item) => ({
    rule_id: item.check_id || null,
    severity: item.extra?.severity || null,
    message: item.extra?.message || null,
    path: item.path || null,
    start_line: item.start?.line || null,
    end_line: item.end?.line || null
  }));

  const stderr = await fs.readFile(paths.stderr, "utf8").catch(() => "");

  return {
    success: true,
    job_id,
    status: meta.status,
    tool: "semgrep",
    image: meta.image,
    repo: meta.repo,
    scope: meta.scope,
    profile: meta.profile,
    created_at: meta.created_at,
    started_at: meta.started_at,
    finished_at: meta.finished_at,
    repo_path: meta.repo_path,
    target_path: meta.target_path,
    container_target_path: meta.container_target_path,
    summary: meta.summary,
    findings,
    errors: parsed.errors || [],
    stderr
  };
}

async function listJobs() {
  await ensureDir(JOBS_BASE_DIR);
  const entries = await fs.readdir(JOBS_BASE_DIR, { withFileTypes: true });
  const jobs = [];

  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const meta = await readJson(path.join(JOBS_BASE_DIR, entry.name, "job.json"));
    if (!meta) continue;

    jobs.push({
      job_id: entry.name,
      status: meta.status,
      repo: meta.repo,
      scope: meta.scope,
      profile: meta.profile,
      created_at: meta.created_at,
      started_at: meta.started_at,
      finished_at: meta.finished_at,
      summary: meta.summary,
      error: meta.error
    });
  }

  jobs.sort((a, b) => String(b.created_at).localeCompare(String(a.created_at)));

  return {
    success: true,
    jobs
  };
}

const server = new Server(
  {
    name: "repo-scan-job-mcp",
    version: "1.0.0"
  },
  {
    capabilities: {
      tools: {}
    }
  }
);

server.setRequestHandler(ListToolsRequestSchema, async () => {
  return {
    tools: [
      {
        name: "repo_list",
        description: "List available repository folders under /repos.",
        inputSchema: {
          type: "object",
          properties: {}
        }
      },
      {
        name: "repo_security_scan_start",
        description:
          "Start a background Semgrep scan job for a repository under /repos. Returns a job_id immediately.",
        inputSchema: {
          type: "object",
          properties: {
            repo: {
              type: "string",
              description:
                "Repository name under /repos, for example 'redback-smartbike-iot'. '/repos/redback-smartbike-iot' is also accepted."
            },
            scope: {
              type: "string",
              description:
                "Optional file or subdirectory inside the repository. Use '.' for the whole repository.",
              default: "."
            },
            profile: {
              type: "string",
              description: "Scan profile",
              enum: ["security", "secrets", "full"],
              default: "security"
            }
          },
          required: ["repo"]
        }
      },
      {
        name: "repo_security_scan_status",
        description: "Check the status of a previously started scan job.",
        inputSchema: {
          type: "object",
          properties: {
            job_id: {
              type: "string",
              description: "Job ID returned by repo_security_scan_start"
            }
          },
          required: ["job_id"]
        }
      },
      {
        name: "repo_security_scan_result",
        description: "Fetch the result of a completed scan job.",
        inputSchema: {
          type: "object",
          properties: {
            job_id: {
              type: "string",
              description: "Job ID returned by repo_security_scan_start"
            }
          },
          required: ["job_id"]
        }
      },
      {
        name: "repo_security_scan_list_jobs",
        description: "List recent scan jobs and their statuses.",
        inputSchema: {
          type: "object",
          properties: {}
        }
      }
    ]
  };
});

server.setRequestHandler(CallToolRequestSchema, async (request) => {
  const { name, arguments: args } = request.params;

  try {
    let result;

    if (name === "repo_list") {
      result = await listRepos();
    } else if (name === "repo_security_scan_start") {
      result = await startScanJob(args || {});
    } else if (name === "repo_security_scan_status") {
      result = await getJobStatus(args || {});
    } else if (name === "repo_security_scan_result") {
      result = await getJobResult(args || {});
    } else if (name === "repo_security_scan_list_jobs") {
      result = await listJobs();
    } else {
      return {
        content: [
          {
            type: "text",
            text: JSON.stringify(
              { success: false, error: `Unknown tool: ${name}` },
              null,
              2
            )
          }
        ],
        isError: true
      };
    }

    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(result, null, 2)
        }
      ]
    };
  } catch (err) {
    return {
      content: [
        {
          type: "text",
          text: JSON.stringify(
            { success: false, error: err.message },
            null,
            2
          )
        }
      ],
      isError: true
    };
  }
});

const transport = new StdioServerTransport();
await server.connect(transport);
